In [1]:
import pandas as pd
import numpy as np

In [4]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [10]:
date['date_year'] = date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

In [11]:
date['date_month'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [12]:
date['date_day'] = date['date'].dt.day
date.head()

        date  product_id  city_id  orders  date_year  date_month  date_day
0 2019-12-10        5628       25       3       2019          12        10
1 2018-08-15        3646       14     157       2018           8        15
2 2018-10-23        1859       25       1       2018          10        23
3 2019-08-17        7292       25       1       2019           8        17
4 2019-01-06        4344       25       3       2019           1         6

In [14]:
date['date_month_name'] = date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name
0,2019-12-10,5628,25,3,2019,12,10,December
1,2018-08-15,3646,14,157,2018,8,15,August
2,2018-10-23,1859,25,1,2018,10,23,October
3,2019-08-17,7292,25,1,2019,8,17,August
4,2019-01-06,4344,25,3,2019,1,6,January

In [15]:
date['dayofweek'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,dayofweek
0,2019-12-10,5628,25,3,2019,12,10,December,1
1,2018-08-15,3646,14,157,2018,8,15,August,2
2,2018-10-23,1859,25,1,2018,10,23,October,1
3,2019-08-17,7292,25,1,2019,8,17,August,5
4,2019-01-06,4344,25,3,2019,1,6,January,6

In [22]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders'])
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,dayofweek,date_dow_name
413,2019-08-01,836,0,1,2019,8,1,August,3,Thursday
454,2019-10-15,1766,22,15,2019,10,15,October,1,Tuesday
337,2019-07-15,4180,16,1,2019,7,15,July,0,Monday
73,2019-07-28,3913,13,19,2019,7,28,July,6,Sunday
343,2019-03-22,3064,8,2,2019,3,22,March,4,Friday

In [24]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,dayofweek,date_dow_name,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,10,December,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,15,August,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,23,October,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,17,August,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,6,January,6,Sunday,1

In [27]:
date['weekofYear'] = date['date'].dt.isocalendar().week
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,dayofweek,date_dow_name,date_is_weekend,weekofYear
0,2019-12-10,5628,25,3,2019,12,10,December,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,15,August,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,23,October,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,17,August,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,6,January,6,Sunday,1,1

In [29]:
date['quarter'] = date['date'].dt.quarter
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,dayofweek,date_dow_name,date_is_weekend,weekofYear,quarter
0,2019-12-10,5628,25,3,4,12,10,December,1,Tuesday,0,50,4
1,2018-08-15,3646,14,157,3,8,15,August,2,Wednesday,0,33,3
2,2018-10-23,1859,25,1,4,10,23,October,1,Tuesday,0,43,4
3,2019-08-17,7292,25,1,3,8,17,August,5,Saturday,1,33,3
4,2019-01-06,4344,25,3,1,1,6,January,6,Sunday,1,1,1

In [54]:
import datetime
today =datetime.datetime.today()
today

datetime.datetime(2026, 2, 5, 17, 13, 13, 278616)

In [39]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [42]:
time['date'] = pd.to_datetime(time['date'])

In [45]:
time['year'] = time['date'].dt.year
time['month'] = time['date'].dt.month
time['day'] = time['date'].dt.day
time.head()

,date,msg,year,month,day
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,12,15
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,4,29
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,12,30
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,11,28
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,10,26

In [50]:
time['hour'] = time['date'].dt.hour
time['minutes'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second
time['time'] = time['date'].dt.time
time.head()

,date,msg,year,month,day,hour,minutes,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,12,15,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,4,29,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,12,30,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,11,28,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,10,26,23,11,0,23:11:00

In [56]:
import datetime
today =datetime.datetime.today()
today

datetime.datetime(2026, 2, 5, 17, 13, 33, 126251)

In [57]:
today

datetime.datetime(2026, 2, 5, 17, 13, 33, 126251)

In [58]:
today - time['date']

0     4435 days 16:23:33.126251
1     4299 days 17:33:33.126251
2     4785 days 16:52:33.126251
3     4087 days 16:42:33.126251
4     4484 days 18:02:33.126251
                 ...
995   5074 days 16:23:33.126251
996   4395 days 17:59:33.126251
997   4860 days 17:36:33.126251
998   4976 days 17:39:33.126251
999   4248 days 17:48:33.126251
Name: date, Length: 1000, dtype: timedelta64[ns]