In [ ]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv("train.csv",usecols=["SibSp","Parch","Age","Survived",'Pclass'])

In [22]:
df.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [26]:
df.dropna(inplace=True)

In [27]:
X= df.iloc[:,1:5]
y= df['Survived']

In [28]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.6933333333333332)

In [31]:
X['family']= X["SibSp"] + X['Parch']

In [33]:
X.head()

   Pclass   Age  SibSp  Parch  family
0       3  22.0      1      0       1
1       1  38.0      1      0       1
2       3  26.0      0      0       0
3       1  35.0      1      0       1
4       3  35.0      0      0       0

In [36]:
def my_fun(num):
    if num == 1:
        return 0
    elif num>1 & num<=4:
        return 1
    else: 
        return 2

In [37]:
X['family_type'] = X['family'].apply(my_fun)

In [41]:
X.drop(['SibSp','Parch','family'],axis=1)

     Pclass   Age  family_type
0         3  22.0            0
1         1  38.0            0
2         3  26.0            2
3         1  35.0            0
4         3  35.0            2
..      ...   ...          ...
885       3  39.0            1
886       2  27.0            2
887       1  19.0            2
889       1  26.0            2
890       3  32.0            2

[714 rows x 3 columns]

In [42]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.7171825396825398)

In [43]:
df = pd.read_csv('train.csv')

In [44]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [54]:
df['Title'] = df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

In [55]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr